language: node_js
install: npm install
script: LOG_LEVEL=error npm test
cache:
  directories:
  - node_modules
before_deploy:
- echo "All unit tests passed; Preparing to deploy $ENVIRONMENT_NAME"
after_success:
- ENVIRONMENT_NAME=$TRAVIS_BRANCH
- if [ "$TRAVIS_BRANCH" == "master" ]; then ENVIRONMENT_NAME=production; fi
- if [ "$ENVIRONMENT_NAME" == "qa" ]; then AWS_KEY_VAR=AWS_ACCESS_KEY_ID_QA; AWS_SECRET_VAR=AWS_SECRET_ACCESS_KEY_QA;
  fi
- if [ "$ENVIRONMENT_NAME" == "production" ]; then AWS_KEY_VAR=AWS_ACCESS_KEY_ID_PRODUCTION;
  AWS_SECRET_VAR=AWS_SECRET_ACCESS_KEY_PRODUCTION; fi
- echo "Env name is $ENVIRONMENT_NAME and travis is $TRAVIS_BRANCH"
deploy:
- provider: script
  skip_cleanup: true
  script: "./scripts/travis-deploy.sh $ENVIRONMENT_NAME"
  on:
    all_branches: true
    # Note: development deploys are disabled:
    condition: "$ENVIRONMENT_NAME =~ ^qa|production$"
- provider: script
  script: ./node_modules/.bin/node-lambda package -e "$ENVIRONMENT_NAME"
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$ENVIRONMENT_NAME =~ ^qa|production$"
- provider: s3
  access_key_id: "${!AWS_KEY_VAR}"
  secret_access_key: "${!AWS_SECRET_VAR}"
  bucket: nypl-travis-builds-$ENVIRONMENT_NAME
  skip_cleanup: true
  local_dir: build
  on:
    all_branches: true
    condition: "$ENVIRONMENT_NAME =~ ^qa|production$"
after_deploy: echo "Successfully executed deploy trigger for $ENVIRONMENT_NAME"
env:
  global:
    secure: lzeWEulqWP6wC4VFXIsCfaljL3wIzVwveLdGC69scI55U5EMyuiD54aTCLFIz9ESyBauMsFHhNkuK0TAF+1j3RUJgxAtzoKCSvCOLWeJLZBlP8ynYZW4YC27oP9iQUAB1QmSmFXvDosbs1c0IHK2W3oDu2gNeUyjGq5yXM7I0hr+AdnmMUPcYBQ6u4KSDESKPD0ZyeWXCG1vNbOZMLa9p1Dcjy5UwMsytNbdjfHqspeZG1dkm5WRKoBoHR9q1LDoNznaJg26qLg98iBZsE1k9WlgOd5a8LZB3KnPr4uAxhyToDagpEeQ1/tolEpvsSIHoBUuwVOPQwbecmO7ZH+KrLCvITxHJaJ3qP9AvfhJz0I9IjTPZtp1t6HEapH4APnX//b4J4+W3BbG5HHmJdvdPmtfYAWVDTrZuO4tSHfWqVmuzZ4RRKGKQHEoiP0aSWsg6jf7gAI5QqqVqKqcyV9KKN1FreAV4VK0U5Z6t6nS05PEmMLTNLWISjwmtkNswFxGut3ZTiUJoy69o81hUQRP3q6dKq5d0M7EQmNf8rjJIvfkGnNNQI7BG8yuzsD3mPQ++O+kK1osOPV4+4B24Ko0h0RWtJK8dp01U6u5BEXVfMYHS+CQXKrx3C6MxBXGpr4t41g1Z/+Z55PUE9Rd73KhhEbJh4lHoaLgu1q+HxARsLM=
