language: node_js
install: npm install
script: LOG_LEVEL=error npm test
cache:
  directories:
  - node_modules
before_deploy:
- echo "All unit tests passed; Preparing to deploy $ENVIRONMENT_NAME"
after_success:
- ENVIRONMENT_NAME=$TRAVIS_BRANCH
- if [ "$TRAVIS_BRANCH" == "master" ]; then ENVIRONMENT_NAME=production; fi
- if [ "$ENVIRONMENT_NAME" == "qa" ]; then AWS_KEY_VAR=AWS_ACCESS_KEY_ID_QA; AWS_SECRET_VAR=AWS_SECRET_ACCESS_KEY_QA;
  fi
- if [ "$ENVIRONMENT_NAME" == "production" ]; then AWS_KEY_VAR=AWS_ACCESS_KEY_ID_PRODUCTION;
  AWS_SECRET_VAR=AWS_SECRET_ACCESS_KEY_PRODUCTION; fi
- echo "Env name is $ENVIRONMENT_NAME and travis is $TRAVIS_BRANCH"
deploy:
- provider: script
  skip_cleanup: true
  script: "./scripts/travis-deploy.sh $ENVIRONMENT_NAME"
  on:
    all_branches: true
    condition: "$ENVIRONMENT_NAME =~ ^qa|production$"
- provider: script
  script: ./node_modules/.bin/node-lambda package -e "$ENVIRONMENT_NAME"
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$ENVIRONMENT_NAME =~ ^qa|production$"
- provider: s3
  access_key_id: "${!AWS_KEY_VAR}"
  secret_access_key: "${!AWS_SECRET_VAR}"
  bucket: nypl-travis-builds-$ENVIRONMENT_NAME
  skip_cleanup: true
  local_dir: build
  on:
    all_branches: true
    condition: "$ENVIRONMENT_NAME =~ ^qa|production$"
after_deploy: echo "Successfully executed deploy trigger for $ENVIRONMENT_NAME"
env:
  global:
    secure: rY7aZojWkR1jEe7ULe0bMJIz30o+JG09d4RqQG7OssqnniD0gyUzD+7tCWE3iPvpomSVsEo2RIb+M6qvZ/O61nvAQNZ5m2hfZSi6GzDtpVYXKP1C5sFtX4K6hJr2+RH7bQ6BQXkzZ3RpG36vDxfbDXabn8voyP+p2G9gMRVb/owl1knQwD60E9CGmbQLOhLU5F08jtbXow/a45+DLGpoQ2v8BLLdrknwlFlErvLPD2vXVqFxrqea9RiklyePe75DUvMjt/VeUQY/XoUwqPlFCh4cGq0/dnT9o9TCsc7KWf9kiGx6OARgFSSq3D7WsyqykxH0iDCTGCH+HkbU8FLdysAkW4nHCcYg/pugJ/gKud1nXf4xoUwVj3rIfnFuZElgqGLkYRHpVielqq13CjqajKB4M6KJhd2oXVGhQfwWnQ5U005Dv1oAAoxdoyEcnaEhwC02H8BHQZSVLa7owWhk5T+D4oubRlbZecaV4Vt48XAvpQIhbrol1ZVNnusidfV2j8N/VW9R+WmdE6BtTWT8ObWugPCpC2lPD4Rdyx6K61KsnMsgB2aUFsa6Y5OfnKxo7KAqBOGuVxnsq1CWo6BbNPo5KDtSxGHYrwtUrCzSj7VjDVoeK+7uYfd9Hwo2pU+7HIkhSfOUBytQ0+P5b7U5P2f5p1WTFXxU3Lf6iQ5f53E=
